parameters:
#    troiswa_blog.example.class: Troiswa\BlogBundle\Example

services:
#    troiswa_blog.example:
#        class: %troiswa_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
