<?php

namespace Troiswa\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function findAllByDateDesc()
    {
        return $this -> getEntityManager() -> createQuery('SELECT a FROM TroiswaBlogBundle:Article a ORDER BY a.dateCreation DESC') -> getResult();
    }

    public function countArticle()
    {
        // return $this -> getEntityManager() -> createQuery('SELECT COUNT (a) FROM TroiswaBlogBundle:Article a') -> getSingleScalarResult();
        return $this -> createQueryBuilder('a') -> select('COUNT(a)') -> getQuery() -> getSingleScalarResult();
    }

    /*
    public function myFind($id)
    {
        return $this -> getEntityManager() -> createQuery ('SELECT a FROM TroiswaBlogBundle:Article a WHERE a.id = :id') -> setParameter ('id',$id) -> getResult();
    }
    */

    public function popularArticles($tab = null)
    {
        if(is_null($tab))
            return $this -> getEntityManager() -> createQuery ('SELECT a FROM TroiswaBlogBundle:Article a WHERE a.cover = 1') -> getResult();
        else
            return $this -> getEntityManager() -> createQuery ('SELECT a FROM TroiswaBlogBundle:Article a WHERE a.id IN (:list)') -> setParameter ('list',$tab) -> getResult();
    }

    public function findAllByCategory($id)
    {
            return $this -> getEntityManager() -> createQuery ('SELECT a FROM TroiswaBlogBundle:Article a JOIN a.category c WHERE c.id = :idcategory') -> setParameter ('idcategory', $id) -> getResult();
    }

}
